version: "3.8"

services:
  kanban-ui:
    container_name: kanban-ui
    build:
      context: ./kanban-frontend-develop
    networks:
      - kanban-network

  kanban-app:
    container_name: kanban-app
    build:
      context: ./kanban-backend-develop
    environment:
      - JAVA_OPTS=-Xmx512m
    depends_on:
      - kanban-postgres
    networks:
      - kanban-network

  kanban-postgres:
    image: postgres:13
    container_name: kanban-postgres
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    networks:
      - kanban-network
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # SSL certificates path (adjust as needed)
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
    networks:
      - kanban-network
      
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - kanban-network

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - kanban-network

  #loki:
  #  container_name: loki
  #  image: grafana/loki:2.8.0
  #  ports:
  #    - "3100:3100"
  #  command: -config.file=/etc/loki/local-config.yaml
  #  volumes:
  #    - ./loki-config.yaml:/etc/loki/local-config.yaml
  #  networks:
  #    - kanban-network

  promtail:
    container_name: promtail
    image: grafana/promtail:2.8.0
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml    
    networks:
      - kanban-network
      
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - kanban-network
      
networks:
  kanban-network:
