# promtail-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: kubernetes-pods-name
    static_configs:
      - targets:
          - localhost
        labels:
          job: kubernetes-pods-name
          __path__: /var/log/containers/*.log

# For Docker logs, ensure your container logs are accessible at /var/log/containers/
# You might need to mount the log directory into the promtail container.
